### PR TITLE
Fix for @ViewById generic issues

### LINKED ISSUE #1351: ViewById with generics - creates syntax errors in generated class
What steps will reproduce the problem?

Declare something as follows with a generic eg
@ViewById(R.id.phrasetype)
 FloatingLabelItemChooser<ContentValues> phraseTypeSpinner;

This creates syntax errors in the generated class eg bad import and casting error

import com.marvinlabs.widget.floatinglabel.itemchooser.FloatingLabelItemChooser<android.content.ContentValues>;
...
phraseTypeSpinner = ((ContentValues>) hasViews.findViewById(uk.co.myApp.android.R.id.phrasetype));

What version of the product are you using? On what operating system?

3.2, Windows, Android Studio

### PR DESCRIPTION
**Pull request by WonderCsabo**
Fixes #1351.

### CODE REVIEW

File: AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java [hunk 1]
```diff
@@ -527,4 +530,28 @@ public TypeMirror getActualType(Element element, GeneratedClassHolder holder) {
...
+
+	public void addSuppressWarnings(JAnnotatable generatedElement, String annotationValue) {
+		Collection<JAnnotationUse> annotations = generatedElement.annotations();
+		for (JAnnotationUse annotationUse : annotations) {
+			if (annotationUse.getAnnotationClass().fullName().equals(SuppressWarnings.class.getCanonicalName())) {
+				JAnnotationValue value = annotationUse.getAnnotationMembers().values().iterator().next();
+				StringWriter code = new StringWriter();
+				JFormatter formatter = new JFormatter(code);
+				formatter.g(value);
+				if (!code.toString().contains(annotationValue)) {
```
Comment (WonderCsabo) [inline AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java]: I changed this because now we do not need the `TypeElement` passed to this method, which is not always available. I know this is ugly and anti-pattern, but the other way is using 30 lines of reflective code to access the needed values from CodeModel. :worried:

Comment (yDelouis) [inline AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java]: I'm okay with that.

File: AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EComponentWithViewSupportHolder.java [hunk 2]
```diff
@@ -115,7 +119,12 @@ public void assignFindViewById(JFieldRef idRef, JClass viewClass, JFieldRef fiel
 		} else {
 			assignExpression = findViewById(idRef);
 			if (viewClass != null && viewClass != classes().VIEW) {
-				assignExpression = cast(viewClass, assignExpression);
+				JClass targetClass = codeModelHelper.typeMirrorToJClass(annotatedElement.asType(), this);
```
Comment (yDelouis) [inline AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EComponentWithViewSupportHolder.java]: You could use this code (`codeModelHelper.typeMirrorToJClass(annotatedElement.asType(), this)`) in `ViewByIdHandler` so that you don't have to pass the annotatedElement.

Comment (WonderCsabo) [inline AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EComponentWithViewSupportHolder.java]: OK, i'll change it.

**Comment by WonderCsabo** [comment]
PR updated
